meta_product_name: "Artmeets"
meta_title: "The Art Matcher | Artmeets"
meta_description: "Find the art that you have dreamed. Artmeets is a application that allows you to discover new talents everyday!"
meta_image: "https://res.cloudinary.com/clemi04/image/upload/v1638439921/production/artmeets-og-image_1200x630_ksb9bq.png"
# "artmeets-og-image_1200x630.png"
